
spring:
  application:
    name: veganplanet-user
  cloud:
    nacos:
      discovery:
        namespace: veganplanet
        group: JAVA
        server-addr: nacos.vegetarianlefty.com:8848
      config:
        file-extension: yaml
        namespace: veganplanet
        group: JAVA
        server-addr: nacos.vegetarianlefty.com:8848
  config:
    import:
      - optional:nacos:veganplanet-user.yml